general:
  suspendReason: You broke the rules and were suspended!\nFind the forum called Suspensions and look for the post with your name.
  broadcastMessage: true
  printStackTraces: false
database:
  prefix: BrohoofBans_